🔗 :: (#218) CompanySearch 개발
Team-return/JOBIS-DSM-iOS-v2 pull request #225
Opened 2024-04-01 23:58 UTC by ray3238

## 개요
>CompanySearchView의 API 연동, 퍼블리싱

## 작업사항
- CompanySearchView의 API 연동, 퍼블리싱

## UI
<img src="https://github.com/Team-return/JOBIS-DSM-iOS-v2/assets/127665596/a396be06-56ff-4273-b92a-16a9087e6e21.png" width="200" height="400"/>
<img src="https://github.com/Team-return/JOBIS-DSM-iOS-v2/assets/127665596/d831bec6-0fbc-42de-8c25-22bd3a55a3b3.png" width="200" height="400"/>

2024-04-02 00:06 UTC, HongSJae requested changes
`CompanySearch`가 아닌 `SearchCompany`가 좋을 것 같네요

2024-04-03 00:47 UTC, juyeong525 commented on Projects/Presentation/Sources/SearchCompany/SearchCompanyViewController.swift
> +        $0.leftView = UIView(frame: CGRect(x: 0, y: 0, width: 44, height: 0))
leftView에 imageView를 넣을순 없나?

2024-04-03 00:47 UTC, juyeong525 commented on Projects/Presentation/Sources/SearchCompany/SearchCompanyViewModel.swift
> +    public var searchText: String?
public이 private보다 위에 있어야함

2024-04-03 02:20 UTC, winwx commented
## All File Checked ✅
| ✅     | Auto Pull Request SwiftLint Success!!!!     |
|---    |----------------------------------------------    |

2024-04-03 03:10 UTC, juyeong525 commented on Projects/Presentation/Sources/SearchCompany/SearchCompanyViewController.swift
> +        $0.leftView = UIView(frame: CGRect(x: 0, y: 0, width: 44, height: 0))
내가 디자인 시스템으로 뺌 그냥 머지 ㄱㄱ

2024-04-03 03:10 UTC, merged