🔗 :: (#67) 메인 페이지 퍼블리싱
Team-return/JOBIS-DSM-iOS-v2 pull request #75
Opened 2023-12-12 13:45 UTC by HongSJae

## 개요
- 메인 페이지 퍼블리싱

## 작업사항
- 메인 페이지 퍼블리싱 했음
- 학생 정보 뷰 디자인 시스템으로 만듬

## 변경로직

### 변경전

### 변경후

## 사용방법

## 기타
<img width="546" alt="스크린샷 2023-12-12 오후 10 45 40" src="https://github.com/Team-return/JOBIS-DSM-iOS-v2/assets/102791216/c8c3b43c-441f-4f8d-bd97-8f6d1b2ef34a">

2023-12-14 07:16 UTC, BJCHO0501 approved these changes

2023-12-14 07:16 UTC, BJCHO0501 commented on Projects/Presentation/Sources/Home/Alarm/AlarmViewController.swift
> +        $0.isScrollEnabled = true
defalt 가 true여서 없어도 될거 같아요

2023-12-14 07:16 UTC, BJCHO0501 commented on Projects/Presentation/Sources/Home/Components/CareerNavigationCard.swift
> +        }
고쳐서 커밋 ㄱㄱ

2023-12-14 07:16 UTC, BJCHO0501 commented on Projects/Presentation/Sources/MyPage/MyPageViewController.swift
>      }
SectionView 만든건 좋은데 이거 클릭했을때 이벤트 처리 어케 할거여??

2023-12-14 07:18 UTC, HongSJae commented on Projects/Presentation/Sources/Home/Alarm/AlarmViewController.swift
> +        $0.isScrollEnabled = true
ScrollEnabled 말하는 건가요?

2023-12-14 07:18 UTC, HongSJae commented on Projects/Presentation/Sources/Home/Components/CareerNavigationCard.swift
> +        }
이거 다른 PR(API 쪽)에 있습니다

2023-12-14 07:19 UTC, HongSJae commented on Projects/Presentation/Sources/MyPage/MyPageViewController.swift
>      }
MyPage 제가안해서.. 사후 처리는 박주렁님이 해주실 것 같네요

2023-12-14 07:19 UTC, BJCHO0501 commented on Projects/Presentation/Sources/Home/Alarm/AlarmViewController.swift
> +        $0.isScrollEnabled = true
넵넵~1Q!aw2s

2023-12-14 08:37 UTC, juyeong525 commented on Projects/Presentation/Sources/Home/Components/CareerNavigationCard.swift
> +    private var icon = UIImageView()
이런거 imageview붙이면 좋을듯 나중에 헷갈림

2023-12-18 05:06 UTC, juyeong525 requested changes

2023-12-18 05:06 UTC, juyeong525 commented on Projects/Presentation/Sources/Home/Components/Cell/ApplicationStatusCell.swift
> +final class ApplicationStatusCell: UITableViewCell {
ApplicationStatusTableViewCell

2023-12-18 08:33 UTC, juyeong525 approved these changes

2023-12-21 11:16 UTC, merged